// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.31.1
// source: artifact.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ArtifactTypeEnum int32

const (
	ArtifactTypeEnum_UNKNOWN    ArtifactTypeEnum = 0
	ArtifactTypeEnum_TEXT       ArtifactTypeEnum = 1
	ArtifactTypeEnum_IMAGE      ArtifactTypeEnum = 2
	ArtifactTypeEnum_DOCUMENT   ArtifactTypeEnum = 3
	ArtifactTypeEnum_CREDENTIAL ArtifactTypeEnum = 4
	ArtifactTypeEnum_OTHER      ArtifactTypeEnum = 5
)

// Enum value maps for ArtifactTypeEnum.
var (
	ArtifactTypeEnum_name = map[int32]string{
		0: "UNKNOWN",
		1: "TEXT",
		2: "IMAGE",
		3: "DOCUMENT",
		4: "CREDENTIAL",
		5: "OTHER",
	}
	ArtifactTypeEnum_value = map[string]int32{
		"UNKNOWN":    0,
		"TEXT":       1,
		"IMAGE":      2,
		"DOCUMENT":   3,
		"CREDENTIAL": 4,
		"OTHER":      5,
	}
)

func (x ArtifactTypeEnum) Enum() *ArtifactTypeEnum {
	p := new(ArtifactTypeEnum)
	*p = x
	return p
}

func (x ArtifactTypeEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ArtifactTypeEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_artifact_proto_enumTypes[0].Descriptor()
}

func (ArtifactTypeEnum) Type() protoreflect.EnumType {
	return &file_artifact_proto_enumTypes[0]
}

func (x ArtifactTypeEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ArtifactTypeEnum.Descriptor instead.
func (ArtifactTypeEnum) EnumDescriptor() ([]byte, []int) {
	return file_artifact_proto_rawDescGZIP(), []int{0}
}

type Artifact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OwnerId       string                 `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // Unix timestamp
	UpdatedAt     int64                  `protobuf:"varint,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"` // Unix timestamp
	ExpiredAt     int64                  `protobuf:"varint,5,opt,name=expired_at,json=expiredAt,proto3" json:"expired_at,omitempty"` // Unix timestamp
	Type          ArtifactTypeEnum       `protobuf:"varint,6,opt,name=type,proto3,enum=artifact.ArtifactTypeEnum" json:"type,omitempty"`
	MetaInfo      string                 `protobuf:"bytes,7,opt,name=meta_info,json=metaInfo,proto3" json:"meta_info,omitempty"`
	Link          string                 `protobuf:"bytes,8,opt,name=link,proto3" json:"link,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Artifact) Reset() {
	*x = Artifact{}
	mi := &file_artifact_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Artifact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Artifact) ProtoMessage() {}

func (x *Artifact) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Artifact.ProtoReflect.Descriptor instead.
func (*Artifact) Descriptor() ([]byte, []int) {
	return file_artifact_proto_rawDescGZIP(), []int{0}
}

func (x *Artifact) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Artifact) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *Artifact) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Artifact) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *Artifact) GetExpiredAt() int64 {
	if x != nil {
		return x.ExpiredAt
	}
	return 0
}

func (x *Artifact) GetType() ArtifactTypeEnum {
	if x != nil {
		return x.Type
	}
	return ArtifactTypeEnum_UNKNOWN
}

func (x *Artifact) GetMetaInfo() string {
	if x != nil {
		return x.MetaInfo
	}
	return ""
}

func (x *Artifact) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

type ArtifactType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactType) Reset() {
	*x = ArtifactType{}
	mi := &file_artifact_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactType) ProtoMessage() {}

func (x *ArtifactType) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactType.ProtoReflect.Descriptor instead.
func (*ArtifactType) Descriptor() ([]byte, []int) {
	return file_artifact_proto_rawDescGZIP(), []int{1}
}

func (x *ArtifactType) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ArtifactType) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateArtifactRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          ArtifactTypeEnum       `protobuf:"varint,2,opt,name=type,proto3,enum=artifact.ArtifactTypeEnum" json:"type,omitempty"`
	MetaInfo      string                 `protobuf:"bytes,3,opt,name=meta_info,json=metaInfo,proto3" json:"meta_info,omitempty"`
	Link          string                 `protobuf:"bytes,4,opt,name=link,proto3" json:"link,omitempty"`
	ExpiredAt     int64                  `protobuf:"varint,5,opt,name=expired_at,json=expiredAt,proto3" json:"expired_at,omitempty"` // Unix timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateArtifactRequest) Reset() {
	*x = CreateArtifactRequest{}
	mi := &file_artifact_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateArtifactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateArtifactRequest) ProtoMessage() {}

func (x *CreateArtifactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateArtifactRequest.ProtoReflect.Descriptor instead.
func (*CreateArtifactRequest) Descriptor() ([]byte, []int) {
	return file_artifact_proto_rawDescGZIP(), []int{2}
}

func (x *CreateArtifactRequest) GetType() ArtifactTypeEnum {
	if x != nil {
		return x.Type
	}
	return ArtifactTypeEnum_UNKNOWN
}

func (x *CreateArtifactRequest) GetMetaInfo() string {
	if x != nil {
		return x.MetaInfo
	}
	return ""
}

func (x *CreateArtifactRequest) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *CreateArtifactRequest) GetExpiredAt() int64 {
	if x != nil {
		return x.ExpiredAt
	}
	return 0
}

type CreateArtifactResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Artifact      *Artifact              `protobuf:"bytes,1,opt,name=artifact,proto3" json:"artifact,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateArtifactResponse) Reset() {
	*x = CreateArtifactResponse{}
	mi := &file_artifact_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateArtifactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateArtifactResponse) ProtoMessage() {}

func (x *CreateArtifactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateArtifactResponse.ProtoReflect.Descriptor instead.
func (*CreateArtifactResponse) Descriptor() ([]byte, []int) {
	return file_artifact_proto_rawDescGZIP(), []int{3}
}

func (x *CreateArtifactResponse) GetArtifact() *Artifact {
	if x != nil {
		return x.Artifact
	}
	return nil
}

func (x *CreateArtifactResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetArtifactRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArtifactId    string                 `protobuf:"bytes,2,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArtifactRequest) Reset() {
	*x = GetArtifactRequest{}
	mi := &file_artifact_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArtifactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArtifactRequest) ProtoMessage() {}

func (x *GetArtifactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArtifactRequest.ProtoReflect.Descriptor instead.
func (*GetArtifactRequest) Descriptor() ([]byte, []int) {
	return file_artifact_proto_rawDescGZIP(), []int{4}
}

func (x *GetArtifactRequest) GetArtifactId() string {
	if x != nil {
		return x.ArtifactId
	}
	return ""
}

type GetArtifactResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Artifact      *Artifact              `protobuf:"bytes,1,opt,name=artifact,proto3" json:"artifact,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArtifactResponse) Reset() {
	*x = GetArtifactResponse{}
	mi := &file_artifact_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArtifactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArtifactResponse) ProtoMessage() {}

func (x *GetArtifactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArtifactResponse.ProtoReflect.Descriptor instead.
func (*GetArtifactResponse) Descriptor() ([]byte, []int) {
	return file_artifact_proto_rawDescGZIP(), []int{5}
}

func (x *GetArtifactResponse) GetArtifact() *Artifact {
	if x != nil {
		return x.Artifact
	}
	return nil
}

func (x *GetArtifactResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ListArtifactsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	OnPage        int32                  `protobuf:"varint,3,opt,name=on_page,json=onPage,proto3" json:"on_page,omitempty"`
	TypeFilter    ArtifactTypeEnum       `protobuf:"varint,4,opt,name=type_filter,json=typeFilter,proto3,enum=artifact.ArtifactTypeEnum" json:"type_filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListArtifactsRequest) Reset() {
	*x = ListArtifactsRequest{}
	mi := &file_artifact_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListArtifactsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListArtifactsRequest) ProtoMessage() {}

func (x *ListArtifactsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListArtifactsRequest.ProtoReflect.Descriptor instead.
func (*ListArtifactsRequest) Descriptor() ([]byte, []int) {
	return file_artifact_proto_rawDescGZIP(), []int{6}
}

func (x *ListArtifactsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListArtifactsRequest) GetOnPage() int32 {
	if x != nil {
		return x.OnPage
	}
	return 0
}

func (x *ListArtifactsRequest) GetTypeFilter() ArtifactTypeEnum {
	if x != nil {
		return x.TypeFilter
	}
	return ArtifactTypeEnum_UNKNOWN
}

type ListArtifactsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Artifacts     []*Artifact            `protobuf:"bytes,1,rep,name=artifacts,proto3" json:"artifacts,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListArtifactsResponse) Reset() {
	*x = ListArtifactsResponse{}
	mi := &file_artifact_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListArtifactsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListArtifactsResponse) ProtoMessage() {}

func (x *ListArtifactsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListArtifactsResponse.ProtoReflect.Descriptor instead.
func (*ListArtifactsResponse) Descriptor() ([]byte, []int) {
	return file_artifact_proto_rawDescGZIP(), []int{7}
}

func (x *ListArtifactsResponse) GetArtifacts() []*Artifact {
	if x != nil {
		return x.Artifacts
	}
	return nil
}

func (x *ListArtifactsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type UpdateArtifactRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArtifactId    string                 `protobuf:"bytes,2,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"`
	Type          ArtifactTypeEnum       `protobuf:"varint,3,opt,name=type,proto3,enum=artifact.ArtifactTypeEnum" json:"type,omitempty"`
	MetaInfo      string                 `protobuf:"bytes,4,opt,name=meta_info,json=metaInfo,proto3" json:"meta_info,omitempty"`
	Link          string                 `protobuf:"bytes,5,opt,name=link,proto3" json:"link,omitempty"`
	ExpiredAt     int64                  `protobuf:"varint,6,opt,name=expired_at,json=expiredAt,proto3" json:"expired_at,omitempty"` // Unix timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateArtifactRequest) Reset() {
	*x = UpdateArtifactRequest{}
	mi := &file_artifact_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateArtifactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateArtifactRequest) ProtoMessage() {}

func (x *UpdateArtifactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateArtifactRequest.ProtoReflect.Descriptor instead.
func (*UpdateArtifactRequest) Descriptor() ([]byte, []int) {
	return file_artifact_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateArtifactRequest) GetArtifactId() string {
	if x != nil {
		return x.ArtifactId
	}
	return ""
}

func (x *UpdateArtifactRequest) GetType() ArtifactTypeEnum {
	if x != nil {
		return x.Type
	}
	return ArtifactTypeEnum_UNKNOWN
}

func (x *UpdateArtifactRequest) GetMetaInfo() string {
	if x != nil {
		return x.MetaInfo
	}
	return ""
}

func (x *UpdateArtifactRequest) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *UpdateArtifactRequest) GetExpiredAt() int64 {
	if x != nil {
		return x.ExpiredAt
	}
	return 0
}

type UpdateArtifactResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Artifact      *Artifact              `protobuf:"bytes,1,opt,name=artifact,proto3" json:"artifact,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateArtifactResponse) Reset() {
	*x = UpdateArtifactResponse{}
	mi := &file_artifact_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateArtifactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateArtifactResponse) ProtoMessage() {}

func (x *UpdateArtifactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateArtifactResponse.ProtoReflect.Descriptor instead.
func (*UpdateArtifactResponse) Descriptor() ([]byte, []int) {
	return file_artifact_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateArtifactResponse) GetArtifact() *Artifact {
	if x != nil {
		return x.Artifact
	}
	return nil
}

func (x *UpdateArtifactResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DeleteArtifactRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArtifactId    string                 `protobuf:"bytes,2,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteArtifactRequest) Reset() {
	*x = DeleteArtifactRequest{}
	mi := &file_artifact_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteArtifactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteArtifactRequest) ProtoMessage() {}

func (x *DeleteArtifactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteArtifactRequest.ProtoReflect.Descriptor instead.
func (*DeleteArtifactRequest) Descriptor() ([]byte, []int) {
	return file_artifact_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteArtifactRequest) GetArtifactId() string {
	if x != nil {
		return x.ArtifactId
	}
	return ""
}

type DeleteArtifactResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteArtifactResponse) Reset() {
	*x = DeleteArtifactResponse{}
	mi := &file_artifact_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteArtifactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteArtifactResponse) ProtoMessage() {}

func (x *DeleteArtifactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteArtifactResponse.ProtoReflect.Descriptor instead.
func (*DeleteArtifactResponse) Descriptor() ([]byte, []int) {
	return file_artifact_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteArtifactResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetWithOTPRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArtifactId    string                 `protobuf:"bytes,2,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWithOTPRequest) Reset() {
	*x = GetWithOTPRequest{}
	mi := &file_artifact_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWithOTPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWithOTPRequest) ProtoMessage() {}

func (x *GetWithOTPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWithOTPRequest.ProtoReflect.Descriptor instead.
func (*GetWithOTPRequest) Descriptor() ([]byte, []int) {
	return file_artifact_proto_rawDescGZIP(), []int{12}
}

func (x *GetWithOTPRequest) GetArtifactId() string {
	if x != nil {
		return x.ArtifactId
	}
	return ""
}

type GetWithOTPResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Artifact      *Artifact              `protobuf:"bytes,1,opt,name=artifact,proto3" json:"artifact,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWithOTPResponse) Reset() {
	*x = GetWithOTPResponse{}
	mi := &file_artifact_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWithOTPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWithOTPResponse) ProtoMessage() {}

func (x *GetWithOTPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWithOTPResponse.ProtoReflect.Descriptor instead.
func (*GetWithOTPResponse) Descriptor() ([]byte, []int) {
	return file_artifact_proto_rawDescGZIP(), []int{13}
}

func (x *GetWithOTPResponse) GetArtifact() *Artifact {
	if x != nil {
		return x.Artifact
	}
	return nil
}

func (x *GetWithOTPResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	LastSyncTime  int64                  `protobuf:"varint,3,opt,name=last_sync_time,json=lastSyncTime,proto3" json:"last_sync_time,omitempty"` // Unix timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncRequest) Reset() {
	*x = SyncRequest{}
	mi := &file_artifact_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRequest) ProtoMessage() {}

func (x *SyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRequest.ProtoReflect.Descriptor instead.
func (*SyncRequest) Descriptor() ([]byte, []int) {
	return file_artifact_proto_rawDescGZIP(), []int{14}
}

func (x *SyncRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *SyncRequest) GetLastSyncTime() int64 {
	if x != nil {
		return x.LastSyncTime
	}
	return 0
}

type SyncEvent struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	EventId   string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Timestamp int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Unix timestamp
	// Types that are valid to be assigned to EventType:
	//
	//	*SyncEvent_ArtifactCreated
	//	*SyncEvent_ArtifactUpdated
	//	*SyncEvent_ArtifactDeleted
	//	*SyncEvent_SyncComplete
	//	*SyncEvent_ClientConnected
	//	*SyncEvent_ClientDisconnected
	EventType     isSyncEvent_EventType `protobuf_oneof:"event_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncEvent) Reset() {
	*x = SyncEvent{}
	mi := &file_artifact_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncEvent) ProtoMessage() {}

func (x *SyncEvent) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncEvent.ProtoReflect.Descriptor instead.
func (*SyncEvent) Descriptor() ([]byte, []int) {
	return file_artifact_proto_rawDescGZIP(), []int{15}
}

func (x *SyncEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *SyncEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *SyncEvent) GetEventType() isSyncEvent_EventType {
	if x != nil {
		return x.EventType
	}
	return nil
}

func (x *SyncEvent) GetArtifactCreated() *ArtifactCreatedEvent {
	if x != nil {
		if x, ok := x.EventType.(*SyncEvent_ArtifactCreated); ok {
			return x.ArtifactCreated
		}
	}
	return nil
}

func (x *SyncEvent) GetArtifactUpdated() *ArtifactUpdatedEvent {
	if x != nil {
		if x, ok := x.EventType.(*SyncEvent_ArtifactUpdated); ok {
			return x.ArtifactUpdated
		}
	}
	return nil
}

func (x *SyncEvent) GetArtifactDeleted() *ArtifactDeletedEvent {
	if x != nil {
		if x, ok := x.EventType.(*SyncEvent_ArtifactDeleted); ok {
			return x.ArtifactDeleted
		}
	}
	return nil
}

func (x *SyncEvent) GetSyncComplete() *SyncCompleteEvent {
	if x != nil {
		if x, ok := x.EventType.(*SyncEvent_SyncComplete); ok {
			return x.SyncComplete
		}
	}
	return nil
}

func (x *SyncEvent) GetClientConnected() *ClientConnectedEvent {
	if x != nil {
		if x, ok := x.EventType.(*SyncEvent_ClientConnected); ok {
			return x.ClientConnected
		}
	}
	return nil
}

func (x *SyncEvent) GetClientDisconnected() *ClientDisconnectedEvent {
	if x != nil {
		if x, ok := x.EventType.(*SyncEvent_ClientDisconnected); ok {
			return x.ClientDisconnected
		}
	}
	return nil
}

type isSyncEvent_EventType interface {
	isSyncEvent_EventType()
}

type SyncEvent_ArtifactCreated struct {
	ArtifactCreated *ArtifactCreatedEvent `protobuf:"bytes,3,opt,name=artifact_created,json=artifactCreated,proto3,oneof"`
}

type SyncEvent_ArtifactUpdated struct {
	ArtifactUpdated *ArtifactUpdatedEvent `protobuf:"bytes,4,opt,name=artifact_updated,json=artifactUpdated,proto3,oneof"`
}

type SyncEvent_ArtifactDeleted struct {
	ArtifactDeleted *ArtifactDeletedEvent `protobuf:"bytes,5,opt,name=artifact_deleted,json=artifactDeleted,proto3,oneof"`
}

type SyncEvent_SyncComplete struct {
	SyncComplete *SyncCompleteEvent `protobuf:"bytes,6,opt,name=sync_complete,json=syncComplete,proto3,oneof"`
}

type SyncEvent_ClientConnected struct {
	ClientConnected *ClientConnectedEvent `protobuf:"bytes,7,opt,name=client_connected,json=clientConnected,proto3,oneof"`
}

type SyncEvent_ClientDisconnected struct {
	ClientDisconnected *ClientDisconnectedEvent `protobuf:"bytes,8,opt,name=client_disconnected,json=clientDisconnected,proto3,oneof"`
}

func (*SyncEvent_ArtifactCreated) isSyncEvent_EventType() {}

func (*SyncEvent_ArtifactUpdated) isSyncEvent_EventType() {}

func (*SyncEvent_ArtifactDeleted) isSyncEvent_EventType() {}

func (*SyncEvent_SyncComplete) isSyncEvent_EventType() {}

func (*SyncEvent_ClientConnected) isSyncEvent_EventType() {}

func (*SyncEvent_ClientDisconnected) isSyncEvent_EventType() {}

type ArtifactCreatedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Artifact      *Artifact              `protobuf:"bytes,1,opt,name=artifact,proto3" json:"artifact,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactCreatedEvent) Reset() {
	*x = ArtifactCreatedEvent{}
	mi := &file_artifact_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactCreatedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactCreatedEvent) ProtoMessage() {}

func (x *ArtifactCreatedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactCreatedEvent.ProtoReflect.Descriptor instead.
func (*ArtifactCreatedEvent) Descriptor() ([]byte, []int) {
	return file_artifact_proto_rawDescGZIP(), []int{16}
}

func (x *ArtifactCreatedEvent) GetArtifact() *Artifact {
	if x != nil {
		return x.Artifact
	}
	return nil
}

type ArtifactUpdatedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Artifact      *Artifact              `protobuf:"bytes,1,opt,name=artifact,proto3" json:"artifact,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactUpdatedEvent) Reset() {
	*x = ArtifactUpdatedEvent{}
	mi := &file_artifact_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactUpdatedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactUpdatedEvent) ProtoMessage() {}

func (x *ArtifactUpdatedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactUpdatedEvent.ProtoReflect.Descriptor instead.
func (*ArtifactUpdatedEvent) Descriptor() ([]byte, []int) {
	return file_artifact_proto_rawDescGZIP(), []int{17}
}

func (x *ArtifactUpdatedEvent) GetArtifact() *Artifact {
	if x != nil {
		return x.Artifact
	}
	return nil
}

type ArtifactDeletedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArtifactId    string                 `protobuf:"bytes,1,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactDeletedEvent) Reset() {
	*x = ArtifactDeletedEvent{}
	mi := &file_artifact_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactDeletedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactDeletedEvent) ProtoMessage() {}

func (x *ArtifactDeletedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactDeletedEvent.ProtoReflect.Descriptor instead.
func (*ArtifactDeletedEvent) Descriptor() ([]byte, []int) {
	return file_artifact_proto_rawDescGZIP(), []int{18}
}

func (x *ArtifactDeletedEvent) GetArtifactId() string {
	if x != nil {
		return x.ArtifactId
	}
	return ""
}

type SyncCompleteEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SyncTime      int64                  `protobuf:"varint,1,opt,name=sync_time,json=syncTime,proto3" json:"sync_time,omitempty"` // Unix timestamp
	EventsCount   int32                  `protobuf:"varint,2,opt,name=events_count,json=eventsCount,proto3" json:"events_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncCompleteEvent) Reset() {
	*x = SyncCompleteEvent{}
	mi := &file_artifact_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncCompleteEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncCompleteEvent) ProtoMessage() {}

func (x *SyncCompleteEvent) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncCompleteEvent.ProtoReflect.Descriptor instead.
func (*SyncCompleteEvent) Descriptor() ([]byte, []int) {
	return file_artifact_proto_rawDescGZIP(), []int{19}
}

func (x *SyncCompleteEvent) GetSyncTime() int64 {
	if x != nil {
		return x.SyncTime
	}
	return 0
}

func (x *SyncCompleteEvent) GetEventsCount() int32 {
	if x != nil {
		return x.EventsCount
	}
	return 0
}

type ClientHello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	UserAgent     string                 `protobuf:"bytes,2,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	ConnectTime   int64                  `protobuf:"varint,3,opt,name=connect_time,json=connectTime,proto3" json:"connect_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientHello) Reset() {
	*x = ClientHello{}
	mi := &file_artifact_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientHello) ProtoMessage() {}

func (x *ClientHello) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientHello.ProtoReflect.Descriptor instead.
func (*ClientHello) Descriptor() ([]byte, []int) {
	return file_artifact_proto_rawDescGZIP(), []int{20}
}

func (x *ClientHello) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ClientHello) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *ClientHello) GetConnectTime() int64 {
	if x != nil {
		return x.ConnectTime
	}
	return 0
}

type ClientAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Processed     bool                   `protobuf:"varint,2,opt,name=processed,proto3" json:"processed,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientAck) Reset() {
	*x = ClientAck{}
	mi := &file_artifact_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientAck) ProtoMessage() {}

func (x *ClientAck) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientAck.ProtoReflect.Descriptor instead.
func (*ClientAck) Descriptor() ([]byte, []int) {
	return file_artifact_proto_rawDescGZIP(), []int{21}
}

func (x *ClientAck) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *ClientAck) GetProcessed() bool {
	if x != nil {
		return x.Processed
	}
	return false
}

func (x *ClientAck) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ClientConnectedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	UserAgent     string                 `protobuf:"bytes,2,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	ConnectTime   int64                  `protobuf:"varint,3,opt,name=connect_time,json=connectTime,proto3" json:"connect_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientConnectedEvent) Reset() {
	*x = ClientConnectedEvent{}
	mi := &file_artifact_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientConnectedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientConnectedEvent) ProtoMessage() {}

func (x *ClientConnectedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientConnectedEvent.ProtoReflect.Descriptor instead.
func (*ClientConnectedEvent) Descriptor() ([]byte, []int) {
	return file_artifact_proto_rawDescGZIP(), []int{22}
}

func (x *ClientConnectedEvent) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ClientConnectedEvent) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *ClientConnectedEvent) GetConnectTime() int64 {
	if x != nil {
		return x.ConnectTime
	}
	return 0
}

type ClientDisconnectedEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ClientId       string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	DisconnectTime int64                  `protobuf:"varint,2,opt,name=disconnect_time,json=disconnectTime,proto3" json:"disconnect_time,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ClientDisconnectedEvent) Reset() {
	*x = ClientDisconnectedEvent{}
	mi := &file_artifact_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientDisconnectedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientDisconnectedEvent) ProtoMessage() {}

func (x *ClientDisconnectedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientDisconnectedEvent.ProtoReflect.Descriptor instead.
func (*ClientDisconnectedEvent) Descriptor() ([]byte, []int) {
	return file_artifact_proto_rawDescGZIP(), []int{23}
}

func (x *ClientDisconnectedEvent) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ClientDisconnectedEvent) GetDisconnectTime() int64 {
	if x != nil {
		return x.DisconnectTime
	}
	return 0
}

var File_artifact_proto protoreflect.FileDescriptor

const file_artifact_proto_rawDesc = "" +
	"\n" +
	"\x0eartifact.proto\x12\bartifact\"\xf3\x01\n" +
	"\bArtifact\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\tR\aownerId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\x03R\tupdatedAt\x12\x1d\n" +
	"\n" +
	"expired_at\x18\x05 \x01(\x03R\texpiredAt\x12.\n" +
	"\x04type\x18\x06 \x01(\x0e2\x1a.artifact.ArtifactTypeEnumR\x04type\x12\x1b\n" +
	"\tmeta_info\x18\a \x01(\tR\bmetaInfo\x12\x12\n" +
	"\x04link\x18\b \x01(\tR\x04link\"2\n" +
	"\fArtifactType\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x97\x01\n" +
	"\x15CreateArtifactRequest\x12.\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1a.artifact.ArtifactTypeEnumR\x04type\x12\x1b\n" +
	"\tmeta_info\x18\x03 \x01(\tR\bmetaInfo\x12\x12\n" +
	"\x04link\x18\x04 \x01(\tR\x04link\x12\x1d\n" +
	"\n" +
	"expired_at\x18\x05 \x01(\x03R\texpiredAt\"^\n" +
	"\x16CreateArtifactResponse\x12.\n" +
	"\bartifact\x18\x01 \x01(\v2\x12.artifact.ArtifactR\bartifact\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"5\n" +
	"\x12GetArtifactRequest\x12\x1f\n" +
	"\vartifact_id\x18\x02 \x01(\tR\n" +
	"artifactId\"[\n" +
	"\x13GetArtifactResponse\x12.\n" +
	"\bartifact\x18\x01 \x01(\v2\x12.artifact.ArtifactR\bartifact\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x80\x01\n" +
	"\x14ListArtifactsRequest\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x17\n" +
	"\aon_page\x18\x03 \x01(\x05R\x06onPage\x12;\n" +
	"\vtype_filter\x18\x04 \x01(\x0e2\x1a.artifact.ArtifactTypeEnumR\n" +
	"typeFilter\"_\n" +
	"\x15ListArtifactsResponse\x120\n" +
	"\tartifacts\x18\x01 \x03(\v2\x12.artifact.ArtifactR\tartifacts\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xb8\x01\n" +
	"\x15UpdateArtifactRequest\x12\x1f\n" +
	"\vartifact_id\x18\x02 \x01(\tR\n" +
	"artifactId\x12.\n" +
	"\x04type\x18\x03 \x01(\x0e2\x1a.artifact.ArtifactTypeEnumR\x04type\x12\x1b\n" +
	"\tmeta_info\x18\x04 \x01(\tR\bmetaInfo\x12\x12\n" +
	"\x04link\x18\x05 \x01(\tR\x04link\x12\x1d\n" +
	"\n" +
	"expired_at\x18\x06 \x01(\x03R\texpiredAt\"^\n" +
	"\x16UpdateArtifactResponse\x12.\n" +
	"\bartifact\x18\x01 \x01(\v2\x12.artifact.ArtifactR\bartifact\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"8\n" +
	"\x15DeleteArtifactRequest\x12\x1f\n" +
	"\vartifact_id\x18\x02 \x01(\tR\n" +
	"artifactId\".\n" +
	"\x16DeleteArtifactResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"4\n" +
	"\x11GetWithOTPRequest\x12\x1f\n" +
	"\vartifact_id\x18\x02 \x01(\tR\n" +
	"artifactId\"Z\n" +
	"\x12GetWithOTPResponse\x12.\n" +
	"\bartifact\x18\x01 \x01(\v2\x12.artifact.ArtifactR\bartifact\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"P\n" +
	"\vSyncRequest\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12$\n" +
	"\x0elast_sync_time\x18\x03 \x01(\x03R\flastSyncTime\"\xa0\x04\n" +
	"\tSyncEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12K\n" +
	"\x10artifact_created\x18\x03 \x01(\v2\x1e.artifact.ArtifactCreatedEventH\x00R\x0fartifactCreated\x12K\n" +
	"\x10artifact_updated\x18\x04 \x01(\v2\x1e.artifact.ArtifactUpdatedEventH\x00R\x0fartifactUpdated\x12K\n" +
	"\x10artifact_deleted\x18\x05 \x01(\v2\x1e.artifact.ArtifactDeletedEventH\x00R\x0fartifactDeleted\x12B\n" +
	"\rsync_complete\x18\x06 \x01(\v2\x1b.artifact.SyncCompleteEventH\x00R\fsyncComplete\x12K\n" +
	"\x10client_connected\x18\a \x01(\v2\x1e.artifact.ClientConnectedEventH\x00R\x0fclientConnected\x12T\n" +
	"\x13client_disconnected\x18\b \x01(\v2!.artifact.ClientDisconnectedEventH\x00R\x12clientDisconnectedB\f\n" +
	"\n" +
	"event_type\"F\n" +
	"\x14ArtifactCreatedEvent\x12.\n" +
	"\bartifact\x18\x01 \x01(\v2\x12.artifact.ArtifactR\bartifact\"F\n" +
	"\x14ArtifactUpdatedEvent\x12.\n" +
	"\bartifact\x18\x01 \x01(\v2\x12.artifact.ArtifactR\bartifact\"7\n" +
	"\x14ArtifactDeletedEvent\x12\x1f\n" +
	"\vartifact_id\x18\x01 \x01(\tR\n" +
	"artifactId\"S\n" +
	"\x11SyncCompleteEvent\x12\x1b\n" +
	"\tsync_time\x18\x01 \x01(\x03R\bsyncTime\x12!\n" +
	"\fevents_count\x18\x02 \x01(\x05R\veventsCount\"l\n" +
	"\vClientHello\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x02 \x01(\tR\tuserAgent\x12!\n" +
	"\fconnect_time\x18\x03 \x01(\x03R\vconnectTime\"Z\n" +
	"\tClientAck\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1c\n" +
	"\tprocessed\x18\x02 \x01(\bR\tprocessed\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"u\n" +
	"\x14ClientConnectedEvent\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x02 \x01(\tR\tuserAgent\x12!\n" +
	"\fconnect_time\x18\x03 \x01(\x03R\vconnectTime\"_\n" +
	"\x17ClientDisconnectedEvent\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12'\n" +
	"\x0fdisconnect_time\x18\x02 \x01(\x03R\x0edisconnectTime*]\n" +
	"\x10ArtifactTypeEnum\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\b\n" +
	"\x04TEXT\x10\x01\x12\t\n" +
	"\x05IMAGE\x10\x02\x12\f\n" +
	"\bDOCUMENT\x10\x03\x12\x0e\n" +
	"\n" +
	"CREDENTIAL\x10\x04\x12\t\n" +
	"\x05OTHER\x10\x052\xaf\x04\n" +
	"\x0fArtifactService\x12S\n" +
	"\x0eCreateArtifact\x12\x1f.artifact.CreateArtifactRequest\x1a .artifact.CreateArtifactResponse\x12J\n" +
	"\vGetArtifact\x12\x1c.artifact.GetArtifactRequest\x1a\x1d.artifact.GetArtifactResponse\x12P\n" +
	"\rListArtifacts\x12\x1e.artifact.ListArtifactsRequest\x1a\x1f.artifact.ListArtifactsResponse\x12S\n" +
	"\x0eUpdateArtifact\x12\x1f.artifact.UpdateArtifactRequest\x1a .artifact.UpdateArtifactResponse\x12S\n" +
	"\x0eDeleteArtifact\x12\x1f.artifact.DeleteArtifactRequest\x1a .artifact.DeleteArtifactResponse\x12G\n" +
	"\n" +
	"GetWithOTP\x12\x1b.artifact.GetWithOTPRequest\x1a\x1c.artifact.GetWithOTPResponse\x126\n" +
	"\x04Sync\x12\x15.artifact.SyncRequest\x1a\x13.artifact.SyncEvent(\x010\x01B.Z,github.com/Maxim-Ba/information-keeper/protob\x06proto3"

var (
	file_artifact_proto_rawDescOnce sync.Once
	file_artifact_proto_rawDescData []byte
)

func file_artifact_proto_rawDescGZIP() []byte {
	file_artifact_proto_rawDescOnce.Do(func() {
		file_artifact_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_artifact_proto_rawDesc), len(file_artifact_proto_rawDesc)))
	})
	return file_artifact_proto_rawDescData
}

var file_artifact_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_artifact_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_artifact_proto_goTypes = []any{
	(ArtifactTypeEnum)(0),           // 0: artifact.ArtifactTypeEnum
	(*Artifact)(nil),                // 1: artifact.Artifact
	(*ArtifactType)(nil),            // 2: artifact.ArtifactType
	(*CreateArtifactRequest)(nil),   // 3: artifact.CreateArtifactRequest
	(*CreateArtifactResponse)(nil),  // 4: artifact.CreateArtifactResponse
	(*GetArtifactRequest)(nil),      // 5: artifact.GetArtifactRequest
	(*GetArtifactResponse)(nil),     // 6: artifact.GetArtifactResponse
	(*ListArtifactsRequest)(nil),    // 7: artifact.ListArtifactsRequest
	(*ListArtifactsResponse)(nil),   // 8: artifact.ListArtifactsResponse
	(*UpdateArtifactRequest)(nil),   // 9: artifact.UpdateArtifactRequest
	(*UpdateArtifactResponse)(nil),  // 10: artifact.UpdateArtifactResponse
	(*DeleteArtifactRequest)(nil),   // 11: artifact.DeleteArtifactRequest
	(*DeleteArtifactResponse)(nil),  // 12: artifact.DeleteArtifactResponse
	(*GetWithOTPRequest)(nil),       // 13: artifact.GetWithOTPRequest
	(*GetWithOTPResponse)(nil),      // 14: artifact.GetWithOTPResponse
	(*SyncRequest)(nil),             // 15: artifact.SyncRequest
	(*SyncEvent)(nil),               // 16: artifact.SyncEvent
	(*ArtifactCreatedEvent)(nil),    // 17: artifact.ArtifactCreatedEvent
	(*ArtifactUpdatedEvent)(nil),    // 18: artifact.ArtifactUpdatedEvent
	(*ArtifactDeletedEvent)(nil),    // 19: artifact.ArtifactDeletedEvent
	(*SyncCompleteEvent)(nil),       // 20: artifact.SyncCompleteEvent
	(*ClientHello)(nil),             // 21: artifact.ClientHello
	(*ClientAck)(nil),               // 22: artifact.ClientAck
	(*ClientConnectedEvent)(nil),    // 23: artifact.ClientConnectedEvent
	(*ClientDisconnectedEvent)(nil), // 24: artifact.ClientDisconnectedEvent
}
var file_artifact_proto_depIdxs = []int32{
	0,  // 0: artifact.Artifact.type:type_name -> artifact.ArtifactTypeEnum
	0,  // 1: artifact.CreateArtifactRequest.type:type_name -> artifact.ArtifactTypeEnum
	1,  // 2: artifact.CreateArtifactResponse.artifact:type_name -> artifact.Artifact
	1,  // 3: artifact.GetArtifactResponse.artifact:type_name -> artifact.Artifact
	0,  // 4: artifact.ListArtifactsRequest.type_filter:type_name -> artifact.ArtifactTypeEnum
	1,  // 5: artifact.ListArtifactsResponse.artifacts:type_name -> artifact.Artifact
	0,  // 6: artifact.UpdateArtifactRequest.type:type_name -> artifact.ArtifactTypeEnum
	1,  // 7: artifact.UpdateArtifactResponse.artifact:type_name -> artifact.Artifact
	1,  // 8: artifact.GetWithOTPResponse.artifact:type_name -> artifact.Artifact
	17, // 9: artifact.SyncEvent.artifact_created:type_name -> artifact.ArtifactCreatedEvent
	18, // 10: artifact.SyncEvent.artifact_updated:type_name -> artifact.ArtifactUpdatedEvent
	19, // 11: artifact.SyncEvent.artifact_deleted:type_name -> artifact.ArtifactDeletedEvent
	20, // 12: artifact.SyncEvent.sync_complete:type_name -> artifact.SyncCompleteEvent
	23, // 13: artifact.SyncEvent.client_connected:type_name -> artifact.ClientConnectedEvent
	24, // 14: artifact.SyncEvent.client_disconnected:type_name -> artifact.ClientDisconnectedEvent
	1,  // 15: artifact.ArtifactCreatedEvent.artifact:type_name -> artifact.Artifact
	1,  // 16: artifact.ArtifactUpdatedEvent.artifact:type_name -> artifact.Artifact
	3,  // 17: artifact.ArtifactService.CreateArtifact:input_type -> artifact.CreateArtifactRequest
	5,  // 18: artifact.ArtifactService.GetArtifact:input_type -> artifact.GetArtifactRequest
	7,  // 19: artifact.ArtifactService.ListArtifacts:input_type -> artifact.ListArtifactsRequest
	9,  // 20: artifact.ArtifactService.UpdateArtifact:input_type -> artifact.UpdateArtifactRequest
	11, // 21: artifact.ArtifactService.DeleteArtifact:input_type -> artifact.DeleteArtifactRequest
	13, // 22: artifact.ArtifactService.GetWithOTP:input_type -> artifact.GetWithOTPRequest
	15, // 23: artifact.ArtifactService.Sync:input_type -> artifact.SyncRequest
	4,  // 24: artifact.ArtifactService.CreateArtifact:output_type -> artifact.CreateArtifactResponse
	6,  // 25: artifact.ArtifactService.GetArtifact:output_type -> artifact.GetArtifactResponse
	8,  // 26: artifact.ArtifactService.ListArtifacts:output_type -> artifact.ListArtifactsResponse
	10, // 27: artifact.ArtifactService.UpdateArtifact:output_type -> artifact.UpdateArtifactResponse
	12, // 28: artifact.ArtifactService.DeleteArtifact:output_type -> artifact.DeleteArtifactResponse
	14, // 29: artifact.ArtifactService.GetWithOTP:output_type -> artifact.GetWithOTPResponse
	16, // 30: artifact.ArtifactService.Sync:output_type -> artifact.SyncEvent
	24, // [24:31] is the sub-list for method output_type
	17, // [17:24] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_artifact_proto_init() }
func file_artifact_proto_init() {
	if File_artifact_proto != nil {
		return
	}
	file_artifact_proto_msgTypes[15].OneofWrappers = []any{
		(*SyncEvent_ArtifactCreated)(nil),
		(*SyncEvent_ArtifactUpdated)(nil),
		(*SyncEvent_ArtifactDeleted)(nil),
		(*SyncEvent_SyncComplete)(nil),
		(*SyncEvent_ClientConnected)(nil),
		(*SyncEvent_ClientDisconnected)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_artifact_proto_rawDesc), len(file_artifact_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_artifact_proto_goTypes,
		DependencyIndexes: file_artifact_proto_depIdxs,
		EnumInfos:         file_artifact_proto_enumTypes,
		MessageInfos:      file_artifact_proto_msgTypes,
	}.Build()
	File_artifact_proto = out.File
	file_artifact_proto_goTypes = nil
	file_artifact_proto_depIdxs = nil
}
